name: final_project_topic6
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas=2.2.2
  - matplotlib=3.9.2
  - scipy=1.13.1
  - scikit-learn=1.5.2
  - jupyter=1.1.1
  - nbformat=5.10.4
